-- 1. Tabla base de Envers que guarda el ID de la revisión (transacción) y el Timestamp (cuándo ocurrió)
CREATE TABLE revinfo (
    rev INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    revtstamp BIGINT
);

-- 2. Tabla espejo de 'billeteras' que guardará el historial de cambios
CREATE TABLE billeteras_aud (
    id BIGINT NOT NULL,
    rev INTEGER NOT NULL,
    revtype SMALLINT, -- 0: Creado, 1: Modificado, 2: Borrado
    usuario_id BIGINT,
    saldo_actual NUMERIC(38,2),
    estado VARCHAR(20),
    version BIGINT,
    fecha_creacion TIMESTAMP,
    PRIMARY KEY (id, rev),
    CONSTRAINT fk_billeteras_aud_revinfo FOREIGN KEY (rev) REFERENCES revinfo(rev)
);